# Generated by Django 3.1.7 on 2021-03-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlc_app', '0003_auto_20210309_0838'),
    ]

    operations = [
    ]
