# Generated by Django 3.1.7 on 2021-03-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlc_app', '0004_auto_20210309_0842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        # migrations.DeleteModel(
        #     name='Recept',
        # ),
    ]
