# Generated by Django 3.1.7 on 2021-03-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlc_app', '0009_auto_20210310_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='recept',
            name='Cook',
            field=models.SmallIntegerField(default=23),
        ),
        migrations.AddField(
            model_name='recept',
            name='Prep',
            field=models.SmallIntegerField(default=2362),
        ),
        migrations.AddField(
            model_name='recept',
            name='Yields',
            field=models.SmallIntegerField(default=586),
        ),
    ]
