# Generated by Django 3.1.7 on 2021-03-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlc_app', '0010_auto_20210311_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recept',
            name='Yields',
            field=models.CharField(default='hhjgjh', max_length=100),
        ),
    ]
