# Generated by Django 3.1.7 on 2021-03-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlc_app', '0013_smallreceipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='smallreceipe',
            name='image',
            field=models.ImageField(null=True, upload_to='news_image'),
        ),
    ]
