# Generated by Django 3.1.7 on 2021-03-15 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlc_app', '0014_smallreceipe_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foods',
        ),
        migrations.DeleteModel(
            name='Smallreceipe',
        ),
    ]
