# Generated by Django 3.1.7 on 2021-03-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlc_app', '0016_recept_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recept',
            name='stars',
            field=models.SmallIntegerField(choices=[(1, 'bir yulduz'), (2, 'ikki yulduz'), (3, 'uch yulduz'), (4, 'tort yulduz'), (5, 'besh yulduz')], default=3),
        ),
    ]
